> train<- read.csv(file.choose())
> test<- read.csv(file.choose())
> attach train
> attach(train)
> train1<- na.omit(train)
> mod<- lm(price2013~state)
>summary(mod)
>mod<- lm(price2013~state+ county)
>options(max.print = 10000)
>summary(mod)
>train1<- read.csv(file.choose())
> mod<- lm(price2013~ zip+ state+ county+ poverty+ price2007)
> summary(mod)
>test$price2013 = rep(0,1063)
>test$price2013 = predict(mod, newdata = test)
>final = data.frame(id = test$id, prediction = test$price2013)
>write.csv(fianl, file = "prediction.csv", row.names = FALSE)