A<- read.csv(file.choose())
> attach(A)
> A$Age_Group<- ifelse(Age<18, "<18", ifelse((Age>=18) & (Age<25), "18-24", ifelse((Age>24) & (Age<35), "25-34", ifelse((Age>34) & (Age<45), "35-44", ifelse((Age>44) & (Age<55), "45-54", ifelse((Age>54) & (Age<65), "55-64", "65+"))))))
> View(A)
> B<- na.omit(A$family_history)
> A$family_history[] <- +(A$family_history=="Yes")
A$Age_Group<- ifelse(Age<18, "<18", ifelse((Age>=18) & (Age<25), "18-24", ifelse((Age>24) & (Age<35), "25-34", ifelse((Age>34) & (Age<45), "35-44", ifelse((Age>44) & (Age<55), "45-54", ifelse((Age>54) & (Age<65), "55-64", "65+"))))))
A[,1] <- ifelse(A[,1] == "Yes", "1", "0")
> View(A)
> A[,6] <- ifelse(A[,6] == "Yes", "1", "0")
> View(A)
> A[,7] <- ifelse(A[,7] == "Yes", "1", "0")
> View(A)
> A[,8] <- ifelse(A[,8] == "Yes", "1", "0")
ggplot(A, aes(A$Age_Group, A$family_history, color= A$tech_company))+geom_point(size=3)
> ggplot(A, aes(A$Age_Group, A$family_history, color= A$self_employed))+geom_point(size=3)
> ggplot(A, aes(A$Age_Group, A$family_history, color= A$remote_work))+geom_point(size=3)
> ggplot(A, aes(A$Age_Group, A$family_history, color= A$treatment))+geom_point(size=3)
> options(repr.plot.width=5, repr.plot.height=5)
> ggplot(A, aes(x=treatment,fill=treatment))+geom_bar(stat="count")+labs(title="Employees Underwent Treatment?")+theme(legend.position = "")
summary(A$Age)
A$Age[which(A$Age<0)]<-20
A$Age[which(A$Age>100)]<-60
summary(A$Age)
ggplot(A, aes(x=no_employees,fill=no_employees))+geom_bar(stat="count")+labs(title="Companies Employee Count")+theme(legend.position = "")
ggplot(A, aes(x=no_employees,y=treatment,fill=treatment))+geom_bar(stat="identity",position="dodge")+labs(title="Employee Counts vs Treatment",y="count")
> barplot(table(A$Age))
> outlier_age <- subset(A[2:4], Age < 16 | Age > 75 )
> nrow(outlier_age)
[1] 3
> age_clean <- subset(A, Age > 16 & Age <60)
> dim(age_clean)
[1] 1248   29
> boxplot(age_clean$Age)
> data <- age_clean
> sapply(data, function(x) sum(is.na(x)))
data <- data[!is.na(data$work_interfere),]
  library("magrittr")
library(dplyr)
data$Gender %<>% tolower
> male_str <- c("male", "m", "male-ish", "maile", "mal", "male (cis)", "make", "male ", "man","msle", "mail", "malr","cis man", "cis male")
> trans_str <- c("trans-female", "something kinda male?", "queer/she/they", "non-binary","nah", "all", "enby", "fluid", "genderqueer", "androgyne", "agender", "male leaning androgynous", "guy (-ish) ^_^", "trans woman", "neuter", "female (trans)", "queer", "ostensibly male, unsure what that really means" )
> female_str <- c("cis female", "f", "female", "woman",  "femake", "female ","cis-female/femme", "female (cis)", "femail")
> data$Gender <- sapply(as.vector(data$Gender), function(x) if(x %in% male_str) "male" else x )
> data$Gender <- sapply(as.vector(data$Gender), function(x) if(x %in% female_str) "female" else x )
> data$Gender <- sapply(as.vector(data$Gender), function(x) if(x %in% trans_str) "trans" else x )
> data %<>% filter(Gender != "a little about you")
data %<>% filter(Gender != "guy (-ish) ^_^")
> data %<>% filter(Gender != "p")
> ggplot(data, aes(data$Age_Group, data$Gender, color= data$Country))+geom_point(size=3)
ggplot(data, aes(data$Country, data$Gender, color= data$Age_Group))+geom_point(size=3)
ggplot(data, aes(data$Country, data$Gender, color= data$Age_Group))+geom_point(size=3)
data %>%select(family_history,treatment)%>%group_by(family_history,treatment)%>%summarise(c=n()) %>%ggplot(aes(x=family_history,y=c,fill=treatment))+geom_bar(stat="identity",position="dodge")+labs(title="Family History vs Treatment",y="count")
data %>%select(Age_Group,treatment)%>%group_by(Age_Group,treatment)%>%summarise(c=n()) %>%ggplot(aes(x=Age_Group,y=c,fill=treatment))+geom_bar(stat="identity",position="dodge")+labs(title="Age Group vs Treatment",y="count")
> data %>%select(tech_company,treatment)%>%group_by(tech_company,treatment)%>%summarise(c=n()) %>%ggplot(aes(x=tech_company,y=c,fill=treatment))+geom_bar(stat="identity",position="dodge")+labs(title="Profession vs Treatment",y="count")
> data %>%select(remote_work,treatment)%>%group_by(remote_work,treatment)%>%summarise(c=n()) %>%ggplot(aes(x=remote_work,y=c,fill=treatment))+geom_bar(stat="identity",position="dodge")+labs(title="Profession vs Treatment",y="count")
> data %>%select(self_employed,treatment)%>%group_by(self_employed,treatment)%>%summarise(c=n()) %>%ggplot(aes(x=self_employed,y=c,fill=treatment))+geom_bar(stat="identity",position="dodge")+labs(title="Profession vs Treatment",y="count")
> data %>%select(work_interfere,treatment)%>%group_by(work_interfere,treatment)%>%summarise(c=n()) %>%ggplot(aes(x=work_interfere,y=c,fill=treatment))+geom_bar(stat="identity",position="dodge")+labs(title="Interferance vs Treatment",y="count")

